[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Node.js Version festlegen
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_SHARP_PATH = "./node_modules/sharp"

# Next.js Plugin f端r automatische Konfiguration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Wichtige Redirects f端r Next.js SPA
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "*"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Response = {status = [404]}}

# Umgebungsvariablen m端ssen 端ber Netlify Dashboard gesetzt werden:
# CARDDAV_URL, ADDRESSBOOK_URL, CARDDAV_USERNAME, CARDDAV_PASSWORD

# KEINE hardcodierten Zugangsdaten hier!

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@node-rs/bcrypt", "sharp"]
  included_files = ["node_modules/sharp/**/*"] 